### ISSUE TITLE
Help: running the "get_des_file_rendering"

### ISSUE THREAD

**Issue by saharad1** [facebookresearch/minihack#93]
Hi, I tried running this by following the guide:
`
from minihack.tiles.rendering import get_des_file_rendering
import IPython.display

def render_des_file(des_file, **kwargs):
    image = get_des_file_rendering(des_file, **kwargs)
    IPython.display.display(image)

des_file = """
MAZE: "mylevel", ' '
FLAGS:premapped
GEOMETRY:center,center
MAP
.....
.....
.....
.....
.....
ENDMAP
"""
render_des_file(des_file, n_images=1, full_screen=False)
`

got the following problem:
`
Traceback (most recent call last):
  File "/Users/saharadmoni/Programming/PycharmProjects/Minihack/main.py", line 29, in <module>
    render_des_file(des_file, n_images=1, full_screen=False)
  File "/Users/saharadmoni/Programming/PycharmProjects/Minihack/main.py", line 13, in render_des_file
    image = get_des_file_rendering(des_file, **kwargs)
  File "/Users/saharadmoni/anaconda3/envs/minihack/lib/python3.8/site-packages/minihack/tiles/rendering.py", line 65, in get_des_file_rendering
    env = MHCustom(
  File "/Users/saharadmoni/anaconda3/envs/minihack/lib/python3.8/site-packages/minihack/tiles/rendering.py", line 43, in __init__
    super().__init__(*args, des_file=des_file, **kwargs)
  File "/Users/saharadmoni/anaconda3/envs/minihack/lib/python3.8/site-packages/minihack/skills.py", line 52, in __init__
    super().__init__(*args, des_file=des_file, **kwargs)
  File "/Users/saharadmoni/anaconda3/envs/minihack/lib/python3.8/site-packages/minihack/base.py", line 271, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/saharadmoni/anaconda3/envs/minihack/lib/python3.8/site-packages/nle/env/tasks.py", line 53, in __init__
    super().__init__(*args, actions=actions, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'archivefile'
`

Ran on Mac silicone conda environment python 3.8.

I would be happy to get help finding a solution.

**Comment by saharad1** [comment]
Hi thanks for the comment.
The environment is:
MiniHack version: 0.1.5+1fe80fc
NLE version: 0.9.0
Gym version: 0.21.0
PyTorch version: 2.0.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 13.4.1
GCC version: Could not collect
CMake version: version 3.27.1

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] libtorch==1.2.0.1
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[conda] libtorch                  1.2.0.1                  pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchaudio                2.0.2                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

**Comment by mahnerak** [comment]
This issue is being closed as we're transitioning maintenance - please track the updated status of this issue at fork: https://github.com/samvelyan/minihack/issues/1
